spring.application.name=airBnbProject

spring.datasource.url=jdbc:mysql://localhost:3306/AirBnbProjectDB
spring.datasource.username=root
spring.datasource.password=Swati@2002

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1